### ISSUE TITLE
Filename problem

### ISSUE THREAD

**Issue by paranoico** [ngocdaothanh/cordova-plugin-unswipable-android-status-bar#2]
Hello and thanks for sharing your work in this plugin.

We are facing a problem:
- File unswipableAndroidStatusBarPlugin.js has the first letter lowercase.
- But in plugin.xml file is named as UnswipableAndroidStatusBarPlugin...

We are using Meteor and have downloaded code to fix it, not sure it only that framework is affected.
Regards.

**Comment by ngocdaothanh** [comment]
Thanks I've fixed the problem. Please uninstall the plugin and install it again.

**Comment by paranoico** [comment]
Thanks a lot.
